### ISSUE TITLE
Unable to fetch commits

### ISSUE THREAD

**Issue by majiang213** [tnesbitt210/interactive-smartlog-issues#16]
**User Report:**

---
**Debug Info:**

*commitsError*: 
```
Error: The remote repo's HEAD does not appear to be tracking a branch. If the remote repo is empty, check out your main branch and run `git push -u origin <branch>`
	at n (/Users/majiang/.vscode/extensions/interactive-smartlog.interactive-smartlog-0.1.62/dist/extension.js:2:589231)
	at /Users/majiang/.vscode/extensions/interactive-smartlog.interactive-smartlog-0.1.62/dist/extension.js:2:589367
	at Array.map (<anonymous>)
	at /Users/majiang/.vscode/extensions/interactive-smartlog.interactive-smartlog-0.1.62/dist/extension.js:2:589335
	at Ku.getRepoInfo (/Users/majiang/.vscode/extensions/interactive-smartlog.interactive-smartlog-0.1.62/dist/extension.js:2:589491)
	at async /Users/majiang/.vscode/extensions/interactive-smartlog.interactive-smartlog-0.1.62/dist/extension.js:2:594947
```

*commitTreesLength*: 0

*uncommittedChangesLength*: 0

*outputChannelContents*: 
```
Setup analytics, session:  425ee15f-83b7-4a25-ab47-31889c406ece1732783110710
Operating System: darwin 24.1.0
IGL Version: 0.1.62
Using cached repo info
Failed to get primary branch using symbolic-ref
[track] ClientConnection  
establish client connection for /Users/majiang/Documents/workspace/ybs/asr
Using cached repo info
Watching 8 critical git paths
Fetching commits...
[track] InitialFetchSmartlogCommits InitialFetchSmartlogCommitsError 
[error] InitialFetchSmartlogCommits InitialFetchSmartlogCommitsError Error: The remote repo's HEAD does not appear to be tracking a branch. If the remote repo is empty, check out your main branch and run `git push -u origin <branch>`
	at n (/Users/majiang/.vscode/extensions/interactive-smartlog.interactive-smartlog-0.1.62/dist/extension.js:2:589231)
	at /Users/majiang/.vscode/extensions/interactive-smartlog.interactive-smartlog-0.1.62/dist/extension.js:2:589367
	at Array.map (<anonymous>)
	at /Users/majiang/.vscode/extensions/interactive-smartlog.interactive-smartlog-0.1.62/dist/extension.js:2:589335
	at Ku.getRepoInfo (/Users/majiang/.vscode/extensions/interactive-smartlog.interactive-smartlog-0.1.62/dist/extension.js:2:589491)
	at async /Users/majiang/.vscode/extensions/interactive-smartlog.interactive-smartlog-0.1.62/dist/extension.js:2:594947
Sending commits to client
Fetching commits...
Sending commits to client
[track] TopLevelErrorShown CommitsFetchError 
[error] TopLevelErrorShown CommitsFetchError Error: The remote repo's HEAD does not appear to be tracking a branch. If the remote repo is empty, check out your main branch and run `git push -u origin <branch>`
	at n (/Users/majiang/.vscode/extensions/interactive-smartlog.interactive-smartlog-0.1.62/dist/extension.js:2:589231)
	at /Users/majiang/.vscode/extensions/interactive-smartlog.interactive-smartlog-0.1.62/dist/extension.js:2:589367
	at Array.map (<anonymous>)
	at /Users/majiang/.vscode/extensions/interactive-smartlog.interactive-smartlog-0.1.62/dist/extension.js:2:589335
	at Ku.getRepoInfo (/Users/majiang/.vscode/extensions/interactive-smartlog.interactive-smartlog-0.1.62/dist/extension.js:2:589491)
	at async /Users/majiang/.vscode/extensions/interactive-smartlog.interactive-smartlog-0.1.62/dist/extension.js:2:594947
Failed to get primary branch using symbolic-ref
[track] FileABug  
```

**Comment by tnesbitt210** [comment]
@majiang213 , can you try the command listed in the error? `git push -u origin main` (or substitute what ever branch you're using for "main")

**Comment by tnesbitt210** [comment]
Closing since I haven't heard back, but feel free to reopen!
