### ISSUE TITLE
Extension or plugin is unresponsive on load more branches

### ISSUE THREAD

**Issue by jcjp** [tnesbitt210/interactive-smartlog-issues#6]
# Description

Extension or plugin is unresponsive after clicking the button load more branches twice. Oldest branch shown is in 2 months, after that it would either infinite load, hide the button or show a modal where visual studio code is stuck.

#### Initial load:
![Initial](https://github.com/tnesbitt210/interactive-smartlog-issues/assets/37642320/fbc68976-d988-4e17-804d-646321a7f097)

#### After loading more branches twice:
![Tail branches](https://github.com/tnesbitt210/interactive-smartlog-issues/assets/37642320/294b5481-643f-48fa-826c-95f044e0ac1b)

#### Developer tools:
![Developer tools](https://github.com/tnesbitt210/interactive-smartlog-issues/assets/37642320/f709a454-f6f8-4cb5-81ba-d748f6860133)

#### Visual studio modal:
![Modal](https://github.com/tnesbitt210/interactive-smartlog-issues/assets/37642320/cd2892c5-db0d-41a3-a85d-aaead59c0592)

# Additional details

### Exact error & trace

Remove some details for brevity, for the specific branch it's my branch with `-backup`.

### Environment / OS:

- Windows 10/11
- Node version 20.11.0
- NPM version 10.2.4
- Visual Studio Code
- Repository is a Vue version 2 application

**Debug Info:**

*commitsError*: 
```JavaScript
Error: `git rev-parse <specific-branch>` returned empty
	at ro.revParse (...interactive-smartlog.interactive-smartlog-0.0.77\dist\extension.js:2:525327)
	at runNextTicks (node:internal/process/task_queues:60:5)
	at listOnTimeout (node:internal/timers:538:9)
	at process.processTimers (node:internal/timers:512:7)
	at async Ru.getCommitInfosOnBranch (...interactive-smartlog.interactive-smartlog-0.0.77\dist\extension.js:2:571791)
	at async Promise.all (index 19)
	at async Ru.getCommitInfos (...interactive-smartlog.interactive-smartlog-0.0.77\dist\extension.js:2:570143)
	at async Ru.getResultAsync (...interactive-smartlog.interactive-smartlog-0.0.77\dist\extension.js:2:572602)
	at async Promise.all (index 1)
	at async ...interactive-smartlog.interactive-smartlog-0.0.77\dist\extension.js:2:563229
```

*commitTreesLength*: 29

*uncommittedChangesLength*: 0

*outputChannelContents*: 
```JavaScript
Setup analytics, session:  dafd...
Operating System: win32 10.0.22631
IGL Version: 0.0.77
Loading repo info...
establish client connection for <location>
[track] ClientConnection  
Loading repo info...
Loaded repo info
Cached repo info
Loaded repo info
Cached repo info
Fetching commits...
Loading commits success
Sending commits to client
Fetching commits...
[track] InitialFetchSmartlogCommits  {"numCommits":11,"numPublicCommits":9,"numBranches":10,"watchmanInstalled":false,"brewInstalled":false}
[track] CommitTreesLoaded  
Loading commits success
Sending commits to client
Fetching commits...
Loading commits success
Sending commits to client
Fetching commits...
Loading commits success
Sending commits to client
Fetching commits...
Loading commits success
Sending commits to client
Fetching commits...
Loading commits success
Sending commits to client
Fetching commits...
Loading commits success
Sending commits to client
Fetching commits...
[track] LoadMoreCommits  {"daysToFetch":60}
Loading commits success
Sending commits to client
Fetching commits...
Loading commits success
Sending commits to client
Fetching commits...
Loading commits success
Sending commits to client
Fetching commits...
Loading commits success
Sending commits to client
Fetching commits...
Loading commits success
Sending commits to client
Fetching commits...
Loading commits success
Sending commits to client
Fetching commits...
Loading commits success
Sending commits to client
Fetching commits...
Loading commits success
Sending commits to client
Fetching commits...
[track] LoadMoreCommits  {"daysToFetch":"Infinity"}
Loading commits failure
Sending commits to client
Fetching commits...
[track] TopLevelErrorShown CommitsFetchError 
[error] TopLevelErrorShown CommitsFetchError Error: `git rev-parse <specific-branch>` returned empty
	at ro.revParse (...interactive-smartlog.interactive-smartlog-0.0.77\dist\extension.js:2:525327)
	at runNextTicks (node:internal/process/task_queues:60:5)
	at listOnTimeout (node:internal/timers:538:9)
	at process.processTimers (node:internal/timers:512:7)
	at async Ru.getCommitInfosOnBranch (...interactive-smartlog.interactive-smartlog-0.0.77\dist\extension.js:2:571791)
	at async Promise.all (index 19)
	at async Ru.getCommitInfos (...interactive-smartlog.interactive-smartlog-0.0.77\dist\extension.js:2:570143)
	at async Ru.getResultAsync (...interactive-smartlog.interactive-smartlog-0.0.77\dist\extension.js:2:572602)
	at async Promise.all (index 1)
	at async ...interactive-smartlog.interactive-smartlog-0.0.77\dist\extension.js:2:563229
```

**Comment by jcjp** [comment]
Here are some of the results of the command you mentioned:
1. `git rev-parse <specific-branch>` returns a hash
2. `git rev-parse refs/heads/<specific-branch>` returns the same hash similar to the from previous command
3. `git log <specific-branch>` it's latest commit is on March 19, 2024
4. a. The only thing unique is we use `/` and `-` e.g. `sample/name-of-branch`
b. Local only already deleted remotely
c. We don't use `git checkout --orphan` but I think this is branched out from another branch vs from our main branch
d. No it's not reference in a `git tag` we only have one tag at the moment I usually add `-backup` or `-v2` to make it unique

**Comment by tnesbitt210** [comment]
Ok, I just pushed v0.0.78. Previously , I was using an npm module called `simple-git` to execute `rev-parse`, but now I'm executing it manually, and logging the output if `rev-parse` doesn't output a valid hash.

Hopefully it's either fixed, or we get some more information about what's going on based on the updated logging.

**Comment by tnesbitt210** [comment]
The debug info just grabs logs from the "output" panel. Do you see anything there?

![image](https://github.com/tnesbitt210/interactive-smartlog-issues/assets/10647853/f2d16dd6-9864-445b-af9a-63505767ba1e)

**Comment by jcjp** [comment]
Wil try again and will let you know, unfortunately I can't interact with most of the buttons in visual studio code when it happens. I'll have the debug tab open before I do my testing.

**Comment by tnesbitt210** [comment]
Sounds good, and give it a try with 0.0.79. I removed some suspicious code, and I added more logs.

**Comment by jcjp** [comment]
Okay I was able to look into the output tab, not sure if it's still loading or should it be completed since it already logged this once.

```JavaScript
Fetching commits...
Loading commits success
Sending commits to client
```

But still continues to log the same continously even if the popup / modal from visual code shows up or it gets stuck.

**Comment by tnesbitt210** [comment]
> log the same continuously

Do you mean that these 3 lines keep logging repeatedly, over and over? If so, that's interesting. Is it just happening on this repo, or others too?

Also... if you _don't_ click "load more branches", then does everything work as expected? Are you able to do things like commit, stage/unstage files, etc?

Thanks again for your help , and I'll look into this in the coming days.

**Comment by jcjp** [comment]
> > log the same continuously
> 
> Do you mean that these 3 lines keep logging repeatedly, over and over? If so, that's interesting. How frequently do they repeat? Like once per second? Once per minute? Is it just happening on one specific repo, or is it happening on all repos?
> 
> Also... if you _don't_ click "load more branches", then does everything work as expected? Are you able to do things like commit, stage/unstage files, etc?
> 
> Thanks again for your help , and I'll look into this in the coming days.

Yes those 3 lines keep repeating every second/s it logs those 3. I haven't tried deeply interacting with it like stage or unstage files but I think it works well on the initial loads of the commit. I can try on my other big repos that has a long history of commits let me see if I can find one.

**Comment by tnesbitt210** [comment]
Sounds good, thanks. I'd suggest trying on the latest version (v0.0.84), because I made some performance improvements. But I suspect those won't fix the issue.

Right now, I'm actually suspecting that this might be a memory issue. That could explain why VSCode starts freezing up, and why it only happens when you load your entire repo history. I wonder if there's some way to validate that on your end by looking at memory usage?

**Comment by jcjp** [comment]
Alright updated the extension and tried it on the repo with issues. It loads the commit hash faster but you are correct still loads the three lines continuously as you mentioned. I monitored my RAM usage via Windows key + G (Xbox game bar?) utilization is at 53% and on Taskmanager memory is at 59%. I have 32GB of physical memory.

**Comment by tnesbitt210** [comment]
Hey @jcjp , I've put in a lot of performance optimizations over the past couple of weeks. They weren't specifically intended to fix the issue you're having, but I wonder if they might've had an effect.

Can you try version 0.1.4 and let me know if this is still happening? Thanks!

**Comment by jcjp** [comment]
> Hey @jcjp , I've put in a lot of performance optimizations over the past couple of weeks. They weren't specifically intended to fix the issue you're having, but I wonder if they might've had an effect.
> 
> Can you try version 0.1.4 and let me know if this is still happening? Thanks!

I tried and still have the same behavior, although this time it shows the modal consistently. I am on version `0.1.5`. Does it happen to others or is it only on my side or Windows? To me it only happens when I try to load more than 2 months worth of commits.

**Comment by tyler-macinnis** [comment]
It happens to me as well, just tried the extension today and same issue.

**Comment by tnesbitt210** [comment]
Sorry it's been so long since I've replied, I was a bit stumped at the time... There's a number of performance improvements that have been made. Could either of you try updating to v0.1.67 and see if there's any improvement?
